server:
  port: 80
  servlet:
    context-path: /
  error:
    path: /error
spring:
  datasource:
    name: springboot
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://114.116.226.207:3306/25000725?serverTimezone=GMT%2B8
#    url: jdbc:mysql://120.79.14.229:3306/25000725?serverTimezone=GMT%2B8
    username: root
    password: Mysql20200909.
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.shiro.demo.pojo

logging:
  level:
    com.shiro.demo.dao: debug
